### ISSUE TITLE
Server rendered page times out on Netlify

### ISSUE THREAD

**Issue by corymsmith** [netlify/netlify-plugin-nextjs#102]
**Describe the bug**

I have a statically rendered page that has Links to other pages like so: <Link href="/shop/groceries">

When I click those links it works correctly, loads the page located at `/pages/shop/[slug].js` and I can see that it fetches the data in the Network tab from:
`https://<MY DOMAIN>/_next/data/54sEZibN3ko1YHo4GqZQg/shop/groceries.json?slug=groceries`

The issue is that if I go directly to `https://<MY DOMAIN>/shop/groceries` in the browser I get a timeout from the Netlify function:

`{"errorMessage":"2021-02-19T23:15:38.032Z 87605de5-c7f5-4d83-aa99-abfd110a2d6a Task timed out after 10.01 seconds"}`

The strange thing is that if I put logs in my `getServerSideProps` and render functions it looks like they run just fine...

All of this works correctly locally but not on Netlify. 

**Versions**
- Next.js: 10.0.7
- plugin (if installed at fixed version): 2.0.1

**If you're using file-based installation**
- netlify.toml:
```
[build]
  command = "npm run build"
  functions = "functions"
  publish = "out"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

**Comment by lindsaylevine** [comment]
@corymsmith hey, thanks for opening this issue :). hmm, hard to say what's going on unfortunately with the info you shared so i've got some questions!

1. if you remove data fetching logic from your getServerSideProps (so that theres effectively nothing in there, return empty props), does it still time out?
2. does this happen on Next 10.0.6 as well? or did it start happening out of the blue?
3. can you provide a reproduction and/or links to your function logs to look at? 

something must be causing it to hang, just not sure at this exact moment :/ happy to help you figure it out though!

**Comment by corymsmith** [comment]
I finally figured this out, had nothing to do with this plugin in the end. 

When I was swapping out a test mobx store for my real one I didn't copy over the code that allows it to work with SSR: 

```
import { enableStaticRendering } from 'mobx-react-lite';
enableStaticRendering(typeof window === 'undefined');
```

The brutal part is that there are no errors or anything and it all works locally!

**Comment by lindsaylevine** [comment]
@corymsmith oh no!!! i wish we were able to surface something more helpful for functions timeouts :/ glad you figured it out!!
