### ISSUE TITLE
[Bug]: When ISR pulls new data on the page and you navigate away and go back the new data is no longer there

### ISSUE THREAD

**Issue by caleblawrence** [netlify/netlify-plugin-nextjs#1061]
### Summary

I have a page that ISR is refreshing data on. It's add a new item to a list and when I click on that item (which is a static page) and then click "back" the newly added ISR data is no longer on the page like it was before. I have to refresh again to get it to show up.

### Steps to reproduce

see summary.

### Plugin version

4.1.1

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Hi @caleblawrence ,
It can take up to 60s for the new data to be available after the stale page is first requested.  

Can you explain the setup of the ISR page? What's the revalidate time? How does adding the item to the list on that page update it right away, or does it only after update after the revalidate time?

**Comment by caleblawrence** [comment]
It's really hard to explain without an example. Here is how to reproduce with this example: https://elegant-brown-75e87c.netlify.app/

Go to the page. Wait 2-3 minutes for it to be ready to service the new page and refresh the page to see the new time. Then click the link on the page. Then click back (browser back) and you'll see the page reverted back to the old stale time instead of the recent one the ISR refreshed it with.

**Comment by ascorbic** [comment]
Ah, I see what's happening! It's down to how internal navigation works. So, when you refresh `/`, it loads the html for that page and kicks-off the regeneration for it. At the next request it serves the fresh HTML. All good. So then you navigate to `/example-static-page` but because you're using next/link it doesn't request the HTML for `/example-static-page`, it instead requests `/_next/static/chunks/pages/example-static-page-yourhash.js` and does an internal navigation (using `history.pushState()`). All fine so far. But then when you use the back button it doesn't actually navigate back to the cached HTML that's in your browser, it instead sends a new request for `/_next/data/yourbuildid/index.json`, which is generated with ISR too. However it's a different request, so it hasn't been refreshed yet, so it sends the old version. This is the exact same thing as will have happened if your had previously navigated there and the browser used the version from the cache. If you refresh the page and try again (i.e. navigate to the static page, then use the back button) you'll then see the new version, because at that point Next.js will request `index.json` again which will have then regenerated. 

Superficially, this seems like a problem: this is unexpected and seems weird. However in the real world this is rarely an issue: real users aren't waiting for `revalidate` timeouts and the refreshing the page to see updates. The contract with ISR is that it's eventually-consistent, and new requests will get the new content. By its nature, ISR is used when it doesn't matter if the data is stale for some users, but you know that it will eventually update. You can be sure that nothing will break, because if you deploy new code it will invalidate everything immediately.

**Comment by caleblawrence** [comment]
Got it. Thanks a lot for your explanation @ascorbic.
