### ISSUE TITLE
Serverless Functions in getStaticProps

### ISSUE THREAD

**Issue by colbyfayock** [netlify/netlify-plugin-nextjs#111]
## Problem

I came across a situation where I was trying to use a serverless function inside of `getStaticProps`

The use case was that I wanted to create a generic function that would `getAll` of something, where I could use that function both in the client and in `getStaticProps`.

That `getAll` function would include a `fetch` to the serverless function, which was maintained in `/pages/api`, which was required to do some auth work on that request.

This seemed to work fine locally on dev, but when I tried to deploy the first time with the new serverless function, it failed.

![image](https://user-images.githubusercontent.com/1045274/110719752-622efe80-81db-11eb-8a61-fa61973d6731.png)

It seems like it's a chicken / egg issue, where due to the order of deployment, the serverless function endpoint isn't available to actually hit inside of that `getStaticProps` request.

## Next.js Support

It looks like this specific use case is documented as not being supported.

![image](https://user-images.githubusercontent.com/1045274/110719886-a6ba9a00-81db-11eb-9978-3b4cb664fc81.png)

https://nextjs.org/docs/basic-features/data-fetching

Probably because of the order of deployment issue. But looks like according to some chatter, their argument is also it avoids extra roundtrip time hitting the request, but that doesn't matter _as_ much with a static deployment since it's at compile time.

## Other Solutions

I realize I can shift some of the code around, where for instance, I can create a server only version of getAll, where I would only use that in getStaticProps and the serverless function, making it reusable, but it seemed like an interesting use case, where thinking more in like a microservices approach, I would think that endpoint should be available to hit when the client gets compiled. I don't think that's the intent of the Next.js functions though

## Next on Netlify

I'm wondering though if this is something resolvable via the plugin. Is the deployment steps fixed? Is it possible to deploy the functions first? 

If I deploy the app without using the serverless function endpoint inside of `getStaticProps`, and follow immediately after that with the request back inside, it works, but that's because it deployed, created it, and at that point, its technically hitting a "stale" function, but with no changes, it ends up working the same.

Curious on your thoughts on that? Definitely a solvable issue by not putting serverless function requests in there, but wondering if that's something that is doable 🤔 

For what it's worth it does the same on Vercel

## Code

Set up a sample repo

https://github.com/colbyfayock/test-functions-netlify

To get it up and running you need to add an environment variable:
```
NEXT_PUBLIC_API_ENDPOINT="http://localhost:3000"
```
Sub in the Netlify URL when deploying

I can reproduce the issue by:
* Connect repo "as is" with no netlify.toml
* Add env variable after generated for API endpoint
* Add Essential Next.js build plugin
* Trigger a new deploy

![image](https://user-images.githubusercontent.com/1045274/110722820-f6e82b00-81e0-11eb-967b-78dd7b81bbce.png)

**Comment by arnars** [comment]
I am running into the exact same issue. Seems illogic that the functions are not available when building the static part of the site.

One solution would be to have a second domain acting as an "external" API, but it would be nice to have these things in the same (build) solution - especially for ease of development.

**Comment by jlengstorf** [comment]
@colbyfayock you're absolutely right that this is a chicken/egg issue

the challenge here is that Netlify deploys are atomic, meaning we don't deploy things partially. this is important for avoiding inconsistent state and complexity with rollbacks, etc.

this means that we _can't_ ship a serverless function before the rest of the site builds without breaking the atomic deploy guarantee

there are two ways to address this:
1. treat the API as a separate service that can be deployed independently (I'm a fan of this option since it keeps the "decoupled" part of the frontend true)
2. create a deployment for the API first, then follow that with a PR to use the API in the frontend. this will work by treating the frontend and the backend (API) as two separate systems that deploy separately
3. export the fetching logic from your API functions so it can be called directly. I've used this before and it works to get around the HTTP request issues as well as keeping the code atomic. for example, you could create `/utils/fetch-data.js` and import that into both `/pages/api/get-data.js` and `/pages/data.js`

in general, though, not allowing a build to call a partially deployed function is a design choice for deployment stability and rollback guarantees. there _might_ be a way to get all of those pieces to fit together, but currently that support isn't planned in Netlify

let me know if the options above won't work for you and we'll see if there are other alternatives available

thanks!

**Comment by colbyfayock** [comment]
cool, yeah. those solutions will definitely work, was mostly wondering if it was doable in a more "pure" way i guess? but makes total sense. thanks!

**Comment by arnars** [comment]
Thanks for the inspiration. 3 is what worked for me. Just made a "static" version of my "local" API call with the same (sort of) logic implemented.

**Comment by jlengstorf** [comment]
@colbyfayock I hear you. ultimately I think keeping deploys atomic is a bigger benefit, but I was also frustrated at first when I hit this

@arnars happy to hear you got it running!

I'm going to close this, but please feel free to follow up with any additional questions!
