### ISSUE TITLE
Support for incremental SSG (ISG/ISR)

### ISSUE THREAD

**Issue by joostmeijles** [netlify/netlify-plugin-nextjs#151]
It seems that next-on-netlify current does not support incremental SSG (https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration).

Are there any plans to support this?

**Comment by dlaugharnTAG** [comment]
Howdy, I had a question about three lines that log out when building:

```
🔥 Copying pre-rendered pages with getStaticProps and JSON data to out
💫 Setting up pages with getStaticProps and fallback: true as Netlify Functions in netlify/functions
💫 Setting up pages with getStaticProps and revalidation interval as Netlify Functions in netlify/functions
```

We have ~25 pages that are pulling from markdown using fs, and they have neither fallback nor revalidation values set, however they all end up logged under Functions bundling, which ends up taking anywhere from 4-7 minutes. Is this expected behavior? The line about copying pre-rendered pages to out would lead me to believe it isn't.

If you can look at build logs, deployment 6058d81084773b0007928857 would be an example.

**Comment by lindsaylevine** [comment]
@dlaugharnTAG howdy! fair question! i believe, per https://github.com/netlify/netlify-plugin-nextjs/blob/main/src/lib/steps/setupPages.js and [here](https://github.com/netlify/netlify-plugin-nextjs/blob/main/src/lib/pages/getStaticPropsWithFallback/setup.js#L10), that we log these lines no matter what. if there are no file names underneath those particular logs you quoted (the file names get logged in the pages loop in setup.js), then there aren't actually functions set up for these files (or there shouldn't be). the line about copying pre-rendered pages to `out` (aka your publish dir) is specifically talking about copying prerendred _html_ to your publish dir. unfortunately, for preview mode, we also have to generate a function for every getStaticProps page. we may consider adding some sort of configurable option to disable preview mode; this wouldn't be the first time someone's given feedback about the additional bloat of our preview mode support.

also: i think i need the whole link to the deploy logs (including the site name) to see them 🤔

**Comment by mikaelgson** [comment]
> the current behavior is temporary. we want to and are aiming to support ISG/ISR in the way that @joostmeijles describes ("true ISR calculates the result in the background and returns the previous result to the user") - or as close to this behavior as possible without compromising our caching and jamstack philosophies.

@lindsaylevine Do you have an estimate on when this will become a reality? This would make Netlify a viable alternative to Vercel for sites depending on ISR.

**Comment by mikaelgson** [comment]
the current behavior is temporary. we want to and are aiming to support ISG/ISR in the way that @joostmeijles describes ("true ISR calculates the result in the background and returns the previous result to the user") - or as close to this behavior as possible without compromising our caching and jamstack philosophies.

@lindsaylevine Do you have an estimate on when this will become a reality? This would make Netlify a viable alternative to Vercel for sites depending on ISR.

**Comment by lindsaylevine** [comment]
@mikaelgson stay tuned 👀 what i can say right now is that we are _a lot_ closer to offering "our version of ISR" than ever before! i will of course be sure to update this thread when i can share more info. :)

**Comment by raaims** [comment]
Hi @lindsaylevine,

We're having [the exact same problem](https://github.com/netlify/netlify-plugin-nextjs/issues/151#issuecomment-805129417). We haven't implemented previews yet but our `getStaticProps` pages are being bundled into functions. Let me know if you need additional information (and where should I send you the info).

Thanks in advance :smile:

**Comment by lindsaylevine** [comment]
@raaims hey! we're considering 2 different options in the near-ish future for this issue. one depends on a delayed internal release, one would be allowing plugin users to turn off preview mode and thus disable functions for getStaticProps pages. because of the first option, we've kindof been playing the waiting game when it comes to solving this issue for the handful of users that have communicated it to us. that said, this issue is unfortunately not really the right place to discuss it; if you want to open a separate issue asking for a solution for the getStaticProps functions stuff, please do!!!! <3

**Comment by lindsaylevine** [comment]
hello all! for those who haven't seen: today netlify announced our first step towards solving the problems ISR/ISG originally set out to solve. 

https://www.netlify.com/blog/2021/04/14/faster-builds-for-large-sites-on-netlify-with-on-demand-builders-now-in-early-access/
https://www.netlify.com/blog/2021/04/14/distributed-persistent-rendering-a-new-jamstack-approach-for-faster-builds/

what i can offer you today is a tagged release of our plugin:
`npm install --save @netlify/plugin-nextjs@experimental-odb`

right now, all this does for "ISR" support is use on-demand builders for getStaticProps pages with `fallback: true` or `fallback: blocking`. that means that any path _not_ prerendered for these static pages will be built once, on demand, and then cached. in the future, we will offer something to accommodate the `revalidate` property and its intended behavior - without compromising the jamstack philosophy. as always, i will keep everyone updated!!!

let me know if you have any questions!

**Comment by tbgse** [comment]
@lindsaylevine first of all thank you for all the amazing work on this plugin 🙏 

We've been exploring Netlify as an alternative to Vercel for our Next project for a while now, and with On-demand Builders this now seems a lot closer to reality. I'm currently trying to plan the internal timelines for us to test next on Netlify with ODB and was wondering how "stable" the experimental branch / ODB is considered at the moment - is this usable for a production environment yet, or should we wait a bit longer? Also curious how close you might be to an implementation of the `revalidate` property 👼

**Comment by lindsaylevine** [comment]
@tbgse thanks for the kind words 😊 i would say the odb branch is reliably stable. it's been in a separate tagged release for 2-ish weeks now for testing and we haven't had any issues reported. that means, within the next week or two, we'll likely merge it into main and release it as the standard/default plugin!

i pinged internally earlier to see how much i could share re: `revalidate` - there is _something_ we have in the works that would address the same problem `revalidate` is specifically trying to solve but can't really say when that's coming or what it is quite yet. as always, hang tight~!!!

**Comment by Nicoowr** [comment]
Hi all,
As a workaround I think it's possible to achieve incremental SSG by combining this plugin (setting `fallback: true` or `blocking`) with [`useSwr`](https://swr.vercel.app/docs/with-nextjs).

**Comment by lindsaylevine** [comment]
updated title to help better direct incoming users looking for ISR stuff :)

**Comment by saidattax** [comment]
Is there way I can trigger the on-demand builder to "rebuild" a particular page?

**Comment by mraerino** [comment]
@saidattax providing this mechanism is something we are very careful with because it is pretty easy to get your site in an inconsistent state with such a capability. since users have no tools to debug this, it would increase the load on our support team to debug sites, which we want to avoid.

I can generally recommend these strategies right now:
- trigger a new deploy using a [Build Hook](https://docs.netlify.com/configure-builds/build-hooks/) if your content changes daily
- not cache your SSR response at all if your content changes hourly or more often

nevertheless we are very interested in hearing about your usecase and how we can solve it better in the future.
would you mind sharing with us what you're trying to achieve and why the options i lined out might not work well for you?

**Comment by saidattax** [comment]
@mraerino Thanks for reply

The content for my sites is updated on-demand from a dashboard. I could indeed trigger a new deploy, but I need the build to be quick. Builds take 30-60 seconds usually. 

The data for the site is fetched from a database. However, in the case of downtime, I'd need a cached version to be sent.

Hence, I wanted to trigger ODBs to build specific pages that need updating.

Thanks

**Comment by tbgse** [comment]
@mraerino we are also waiting for a revalidate feature where we can regenerate pages in the background. We use this for example to allow our marketing team to update localization files, inject experiment data, adjust content in a CMS for a single page etc. those changes will then be picked up during revalidation and updated without requiring a full redeploy.

**Comment by mraerino** [comment]
how would you handle data changes that affect more than one page? e.g. you change the title of a post and a bunch of your category overviews or taxonomy pages need to change?

**Comment by tbgse** [comment]
Since we're running an ecommerce site that is usually not a problem. E.g. we have a ton of marketing related pages, but no real "overview" page where all the titles would be displayed, so there are rarely situations where a change to one page would also impact other places.

The same goes for product pages, e.g. if the description of a single product is updated in our catalog, only that one specific product page would need to change. In other places where this content is used, we would mostly use client side rendering (e.g. in the cart / checkout etc.) so no re-generation would be needed besides that single page re-fetching some of it's data and updating on the edge.

There is of course always a tradeoff that in some situations a user might see stale content or inconsistent content between views - in most cases we deal with that by re-fetching data on the client side and apply modifications as needed. But for us this has mostly been a tradeoff that we've been willing to make if in return it allows us to give a bit more "real time" feel to our stakeholders in marketing / product who make edits to our content, while still having the benefits of SSG.

If you're up for it I'd be happy to connect and walk you through our setup a bit more in detail.

**Comment by mraerino** [comment]
so if one of the stakeholders comes to you saying that some content is outdated, because it was not properly re-validated, how would you debug that situation?

would you just re-deploy the site and wait for the next time this happens?
do you have means to detect this situation inside your stack?
what kind of insights into cached pages would be useful to have on the netlify side?

**Comment by tbgse** [comment]
Right now we're logging into Sentry during revalidation, so if an error occurs during revalidation, we have at least "something" to look at. These errors are very rare for us, and like you said, running a full deploy usually then fixes the problem. Having more insight to debug this would be absolutely fantastic though. 

I guess I could imagine an overview that shows which pages are scheduled for revalidation, when the page was last revalidated and a status marker if the last revalidation was successful or not. Access to a log of the builder would be really helpful too, if it tried to revalidate and ran into errors (e.g. maybe because an API was down while trying to revalidate the content). It would also be quite important that the stale content will continue to be served if the builder runs into an error.

It would be even better if this revalidation could not just be triggered by setting an interval (like it is implemented with next at the moment on vercel) but potentially could also be called directly / through a webhook so that for example CMS updates could immediately trigger a page to be revalidated.

**Comment by selrond** [comment]
Came here after quite a while trying to understand why Netlify doesn't pick up forms.

This should definitely be mentioned somewhere inside the Netlify Form docs, I imagine it's quite common use case.

**Comment by jchan-ne** [comment]
Is there a timeline as to when this will be completed?

**Comment by ptim** [comment]
> what kind of insights into cached pages would be useful to have on the netlify side?

@mraerino response headers indicating the the page render mode and settings would be very helpful - eg: whether SSR or SSG, and if SSG, then fallback and revalidate settings. I understand that this is a NextJS responsibility (I think it probably requires running a custom server at present [[clue](https://gist.github.com/fabb/b1ca994abf2ded0145a917785bc796d7#file-appembeddedwebviewrouter-ts-L37)]), but I'd find this helpful!

> It would be even better if this revalidation could not just be triggered by setting an interval (like it is implemented with next at the moment on vercel) but potentially could also be called directly / through a webhook so that for example CMS updates could immediately trigger a page to be revalidated.

Agreed! Watch the pending NextJS feature: programmatically purging routes

> There's been a lot of discussion here about programmatically purging routes that have been generated with ISR. We're happy to share we're actively working on this now 😄 We've spent the time since this feature launched evaluating options and have come up with a solution we think you'll love.
> [leerob on 23 Apr](https://github.com/vercel/next.js/discussions/11552#discussioncomment-646963)

**Comment by katyperrycbt** [comment]
Hi there, does Netlify support ISR for NextJS app now? It seems that Vercel can support well ISR with 'revalidate' in getStaticProps, and I did use Next Essential plugin in Netlify and still, my static sites are not updated after 'revalidate' interval.

**Comment by tbgse** [comment]
Hey all just curious if there has been any more updates to this topic? It's been a while since the last update. Is it still under consideration to be supported one day?

**Comment by ascorbic** [comment]
@tbgse we have a new release candidate of the build plugin that it worth trying
