### ISSUE TITLE
Server Side Rendering (Netlify Function) and Securtiy (Load Balancing, Ddos Protection)

### ISSUE THREAD

**Issue by paulgrotzke** [netlify/netlify-plugin-nextjs#350]
howdy. 
_I already asked the question in the [Netlify forum](https://answers.netlify.com/t/nextjs-server-side-rendering-netlify-function-and-securtiy-load-balancing-ddos-protection/37805) but was asked to post it here._ 

I found this [article](https://www.netlify.com/blog/2017/03/28/why-you-dont-need-cloudflare-with-netlify/l) from 2017 and I’m not sure how relevant it still is in this regard.

If I understand it correctly, Netlify handles things like load balancing, ddos protection etc. automatically for static pages (if my domain is either registered/ or delegated to Netlify).

Now I’m wondering how this behaves for NextJS sites hosted on Netlify that use server-side rendering with the new Essential Next Plugin. If I understand it correctly, NextJS’s server side rendering is made possible by Netfliy Functions.

Now I’m wondering if Netlify functions have also load balancing, ddos proection, etc. (like the static pages)?
What happens if I have a page on my website that uses the getServerSideProps method and this page is requested very often (on each initial request and for cache invalidation) or is subject to a Ddos attack. Do I have to think about a strategy or does Netfliy handle this automatically for me? If so, how is this working? 

thanks

**Comment by lindsaylevine** [comment]
hello @paulgrotzke! 

serverless functions will auto-scale, so they’re hard to DDoS, but netlify will start charging for function calls. aka, the site won’t go down but after 125K invocations you'd get billed for usage. the best strategy would be to avoid using SSR unless you really need it (e.g. use [ODB](https://docs.netlify.com/configure-builds/on-demand-builders/) whenever possible because it will cache the first server-side build). the plugin uses ODB for you when you use getStaticProps fallback: true for dynamic paths.

let me know if this helps you or if you have additional questions!

**Comment by paulgrotzke** [comment]
hey @lindsaylevine 
thank you, that was the information i needed.
