### ISSUE TITLE
Rename plugin to `@netlify/plugin-nextjs`

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-nextjs#6]
This npm package should probably be renamed from `netlify-plugin-nextjs` to `@netlify/plugin-nextjs` to follow our [naming guidelines](https://github.com/netlify/build/issues/107).

**Comment by verythorough** [comment]
I've posted about this in Slack, but as I think about it, I think it might be worth _not_ changing the name, especially if people are already starting to install it. (I'm not sure if they are yet.)

The current plugin name won't last long, because we'll be replacing it with the core plugin name when we're ready to do that. It's probably easier for us to keep this as-is for now.

**Comment by ehmicky** [comment]
Good point.
This depends on whether we want to:
  - Allow ourselves to do breaking changes -> should keep `netlify-plugin-nextjs`
  - Ensure we keep the alpha users once we're out of alpha -> should use `@netlify/plugin-nextjs`

**Comment by verythorough** [comment]
After [some discussion in Slack](https://netlify.slack.com/archives/C019VHRUF2M/p1603820320009100), we decided to change the package name to [`@netlify/plugin-nextjs`](https://www.npmjs.com/package/@netlify/plugin-nextjs).

Thanks @lindsaylevine for the quick decision-making and action! 🙌
