### ISSUE TITLE
Preview Functions Created

### ISSUE THREAD

**Issue by mansoor292** [netlify/netlify-plugin-nextjs#666]
**Describe the bug**
Next build is adding additional preview functions.  

**To Reproduce**
1. Add page with getStaticPaths/Props
2. No revalidate, fallback: 'blockin'
3. build will add two function next_component and preview_next_component
4. Adding to build times, what are these for

**Expected behavior**
Either do not build the preview function or let us know how it is supposed to be used up.

**Versions**
- Next.js: 11
- plugin (if installed at fixed version): latest

**Comment by lindsaylevine** [comment]
@mansoor292 hello! we're in the middle of a plugin rewrite at the moment that will eliminate the need for this. the reason it's needed is because fallback pages on netlify use ODBs (special serverless functions that cache the first function response) which would interfere with preview behavior. please feel free to downgrade the plugin to 3.7.1 (npm i @netlify/plugin-nextjs@3.7.1) which was the last release before the ODB preview mode support shipped.

**Comment by mansoor292** [comment]
thanks for the quick reply. Here is a suggestion in case you guys want some ideas.

Without revalidate option on netlify (i understand but disagree with reasoning) we are stuck with rebuild to see changes or to implement the preview cookie system that nextjs. If I am using fallback, I only have one shot at building the page.

It would be super cool if you simply generate a preview function, that can be access from a specific path or with a query param that just hits up the getstaticprops even if a page exists in cache. So the current preview function should work automatically if I browse to  https://path?preview=hash or something. 

Currently I have a set of components that are using getServerSideProps to render live previews for content creators and a set of staticpages generated on first browse. Not ideal especially if there already is a preview function.

**Comment by lindsaylevine** [comment]
@mansoor292

>we are stuck with rebuild to see changes or to implement the preview cookie system that nextjs.

i suppose i'm confused - why not implement the preview system? what you're describing here:

>access from a specific path or with a query param that just hits up the getstaticprops even if a page exists in cache.

is what is released in the latest plugin (aka > 3.7.1). that's why there are two functions generated (that add to the build times) -- one is for preview mode, one is for the fallback caching. but you _do_ have to configure preview mode per the next.js docs https://nextjs.org/docs/advanced-features/preview-mode

**Comment by ascorbic** [comment]
Fixed in v4
