### ISSUE TITLE
Having "next export" in npm script fails build, even if unused. 

### ISSUE THREAD

**Issue by racedale** [netlify/netlify-plugin-nextjs#67]
Error message `** Static HTML export next.js projects do not require this plugin **` was caused by `"export": "next export"` existing in my package.json file. I removed "npm run export" from my netlify.toml file when converting my site from SSG to adding some SSR pages, but had left that command in package.json (not documented in any posts that I would need to make sure to remove it). 

Was very _very_ confusing to figure out. I think the easiest fix is updating the error message to be more specific to what is detected. But maybe there is another thing to detect off of? I'm new to Next so not sure. 

[File with detection logic](https://github.com/netlify/netlify-plugin-nextjs/blob/921c95ed10fc381cb919c3e0fa0debc5ed2ab42b/helpers/isStaticExportProject.js)

Also off topic, but for a new NextJS dev the docs around next-on-netlify vs this plugin were confusing. Is next-on-netlify legacy? Is this one the only way to also have custom functions?

**Comment by lindsaylevine** [comment]
hey @racedale thanks so much for bringing this up!!! really value your insight/feedback :). 

1. would love to hear what an ideal error message would've been for you to read/diagnose that build failure! if you don't have one, no worries! i can definitely make it more specific and point devs in the right direction.

2. yes, we need to clarify that :( it's been tough because internally our mission is to make next.js "just work" on netlify. that means in the not so distant future, this plugin will be _automatically installed on all new next.js sites_, without needing to add it yourself. for that reason, we've been unfortunately ambiguous about NoN vs plugin. NoN will likely always exist as its own repo, but using it as a manual install will become "legacy"/deprecated/the uncommon path.

3. yes this is the only way right now to use custom functions and publish dirs!

**Comment by chriscoyier** [comment]
Noting that this just super confused me. I removed the `export` from the `.toml` file, but just that existing at all in `package.json` triggered the failed, even totally unused.

**Comment by gianpaj** [comment]
Hi,

At the bottom of the announcement [blog post](https://www.netlify.com/blog/2020/12/07/announcing-one-click-install-next.js-build-plugin-on-netlify/) it says to deploy:
@cassidoo's https://github.com/cassidoo/next-netlify-starter

I get this error:
```
1:04:57 PM:   Plugin "@netlify/plugin-nextjs" failed                        
1:04:57 PM: ────────────────────────────────────────────────────────────────
1:04:57 PM: ​
1:04:57 PM:   Error message
1:04:57 PM:   Error: ** Static HTML export next.js projects do not require this plugin **
1:04:57 PM: ​
1:04:57 PM:   Plugin details
1:04:57 PM:   Package:        @netlify/plugin-nextjs
1:04:57 PM:   Version:        1.0.2
1:04:57 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
1:04:57 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
1:04:57 PM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
```

I tried:
1. Adding a `next.config.js` like [this](https://github.com/netlify/next-on-netlify-demo/blob/main/next.config.js)
  - It did not work
2. Removing the `npm run export` from the the `netlify.toml` build `command`

See the full deployment log and [code](https://github.com/gianpaj/confettilabs):
https://app.netlify.com/sites/confettilabs/deploys/5fe08f23bbf52800077cfcb7


What GitHub repo should I start with?
- https://github.com/netlify/next-on-netlify-demo or
- https://github.com/cassidoo/next-netlify-starter

Thanks

**Comment by lindsaylevine** [comment]
@gianpaj for the specific repo you linked, remove line 9 from https://github.com/gianpaj/confettilabs/blob/master/package.json#L9

for any repo you start with, don't include any `export` script in your package.json's list of scripts. this has been fixed in main but not published to npm yet unfortunately

**Comment by lindsaylevine** [comment]
just published to npm, pending upgrade here -> https://github.com/netlify/plugins/pull/193

**Comment by gianpaj** [comment]
@lindsaylevine thanks a lot for the quick reply! removing that fixed the deployment!
