### ISSUE TITLE
How can we use this plugin for manual deploys through cli?

### ISSUE THREAD

**Issue by aditya-mitra** [netlify/netlify-plugin-nextjs#74]
First of all, thanks for a very nice and useful plugin.

This plugin works fine when connect to a github repository and installed through the netlify ui.

But, how can I use it deploy my site through the **netlify cli**?
Repository is not connected to github.

I would love an example or demonstration if possible.

**Comment by lindsaylevine** [comment]
hey @aditya-mitra, thanks so much for opening this issue! we had an issue open regarding plugin usage via the CLI for several weeks but happened to transfer it to an internal private repo yesterday, so unfortunately can't reference that for you here, BUT i can summarize! :D 

basically, right now, the plugin will technically "work" with the CLI if you have it installed in your toml file or in the UI of your configured site.

here are the docs for our cli: https://docs.netlify.com/cli/get-started/

in your project directory using the plugin, assuming you've already run `netlify login`, you can run:

`netlify init` 

this will prompt you to either create & configure a new site linked to your netlify account OR to link it to an existing site. sounds like you already have a site for this project from the UI flow, so select the "link to an existing site" option and navigate to your project's site.

from here, you can run `netlify build` or `netlify deploy --build`. this *will* run the plugin. however, if you have a custom publish or functions dir configured, the build will fail on the second run. this is because we haven't yet written logic to "clean" the plugin-generated files between builds/runs for these custom directories.

this is my number one priority at the moment as i've already promised it to @chrisbashton :). unfortunately, it's not super straightforward, so we're getting it done as quickly as we can.

ways around this right now:
1. this is painful, but you _could_ find the plugin-generated files in your custom functions dir/publish dirs and delete them between `netlify build`s. you should be able to identify them via `git status`
2. use the next-on-netlify defaults for the time being -> see https://github.com/netlify/next-on-netlify#3-configure-netlify

i know this was all unnecessarily complicated so i can keep you updated when we have this fixed and supported within the plugin and then it should Just Work TM running `netlify build`. thank you for your patience!!!!!

**Comment by lindsaylevine** [comment]
hey all! i released the plugin with these changes so you should be able to run consecutive builds now with the CLI. we do want to improve this fairly fragile logic for right now and think it will require a lot more thought and attention than we can immediately give so hopefully this just gets people going with the CLI. please see the README for the recommended workflow until we can make it fully seamless and automatic. <3 

cc @chrisbashton

**Comment by uinstinct** [comment]
Thanks for the upgrade.
I will try this plugin one more time
